import express from "express";
import cors from "cors";
import routes from "./routes/index.js";
import {errorHandler} from "./middleware/errorHandler.js";
const app=express();
app.use(cors({origin:process.env.FRONTEND_URL||"http://localhost:5173"}));
app.use(express.json());
app.use("/api",routes);
app.use((req,res)=>res.status(404).json({message:"Rota não encontrada."}));
app.use(errorHandler);
export default app;
